CH-46: Show content for a publisher by clicking on publisher name
h5p/h5p-hub-client pull request #27
Opened 2022-11-04 11:20 UTC by chrieinv

2022-11-04 12:23 UTC, emmachughes requested changes

2022-11-10 08:14 UTC, chrieinv commented on src/scripts/utils/helpers.js
> + *  initials('Donald') => 'Donald'
Updated the examples, did not add a test since running the current tests fails with a config error

2022-11-10 08:18 UTC, chrieinv commented on src/scripts/Components/SelectedPublisher/SelectedPublisher.scss
> +    padding: 1.2em 1.2em 0.975422574em 1em;
The value was copied from a component that sometimes displays in the same location.
I've adjusted the value, any further "rounding" causes a misalignment

2022-11-10 10:46 UTC, emmachughes approved these changes

2022-11-14 08:57 UTC, merged